language: ruby

before_script:
  - bundle exec rake db:migrate RAILS_ENV=test

deploy:
  provider: heroku
  api_key:
    secure: d4byxPzcdJzOqvtp4ZbqDYNJvVEBAZtuAJi13WfEQVoKxorPB9InY3TgMyvYxkkt7O0WiCG3eQzsoIud73fSrPP37cn9K2o+EyPYXxWLz10iZhV1rmSVXGmatq+XdrN7RY9AXhwoy/Rr0oF+KW0hK9dAHWxAWK5wr97j3b9tFYbBMA4VHYACQJA1GsTne8Nxm8TSu+i6bDlLFWD7n4GqYxyC5iBDRyKA9ykFbFg6TArq2HeJlKCUz3iEGsXvrIGZ8wEbJcazAiv1vJmUMq8ZpEq+T2mr8C34eHOpiSeToOaRX2dzuHlIS2XWPqz1Sl4m//tEtFfxPh5+VlnhMPKbJsfS1MlXZ/LqnkbiSu9ebQXNdEj20bD9Bsf/4jKZRjj5mEG0cVVqfwaJ7Jhsmx+cxOUm2gRt2AnKkDNlIZiYur+7pHHTsww/B1bPX7/WG5WphE6l4IASEpVdfLFX7DXVe6vWX99VSFCDZ9Sih2wG55j7PIWWtDRuJE7k+An1AzEmkr4WS9miKUeuAL9I2bUSuKgnSfbMUMkbS1fCPv438u7007sFQmyjBqvVij2gnEhxwWBZHR3SU/5qevOC04YRW/pxo2Gw8ABV9TTcK+BjupDrcaAPAIrVXHfkMqv2DofjMQXd3OSPAgoF4ZLEf7iOT73W/ADk4O84Jd+TvXaT4D0=
  app: shielded-thicket-5793
  on:
    repo: kenchan/tdnm
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/07a29fae-2f04-4390-9fdb-1f694dc328a3
