version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - app
    environment:
      DOMAINS: 'tdnm.localhost -> http://app:3000'
      STAGE: 'local'
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    env_file:
      - tdnm.env
    volumes:
      - .:/app
      - bundler_cache:/app/vendor/bundle
    command: ["bash", "-c", "rm tmp/pids/server.pid 2>/dev/null; bin/rails s -b '0.0.0.0'"]

  db:
    image: "postgres"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - tdnm.env

volumes:
  postgresql_data:
  bundler_cache:
