version: "2"

services:
  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'diary.shu-cream.localhost -> http://app:3000'
      STAGE: 'local'
  app:
    build:
      context: .
    links:
      - db
    environment:
      - "DATABASE_URL=postgres://postgres:postgresql_password@db:5432/tdnm"
      - "RAILS_ENV=production"
      - "TRACKING_ID=UA-00000000-0"
      - "DEFAULT_URL=https://your-host.example.com"
      - "RAILS_MASTER_KEY=MY_MASTER_KEY"
    depends_on:
      - db
  cron:
    build:
      context: .
    command: crond -f -d 8
    links:
      - db
    environment:
      - "DATABASE_URL=postgres://postgres:postgresql_password@db:5432/tdnm"
      - "RAILS_ENV=production"
      - "TRACKING_ID=UA-00000000-0"
      - "DEFAULT_URL=https://your-host.example.com"
      - "RAILS_MASTER_KEY=MY_MASTER_KEY"
    depends_on:
      - db
  db:
    image: "postgres"
    volumes_from:
      - data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgresql_password"
      - "POSTGRES_DB=tdnm"
  data:
    image: "busybox"
    volumes:
      - "/var/lib/postgresql/data"
