version: "2"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'tdnm.localhost -> http://app:3000'
      STAGE: 'local'
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - tdnm.env
    depends_on:
      - db
    volumes:
      - .:/app
    volumes_from:
      - data
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: "postgres"
    volumes_from:
      - data
    env_file:
      - tdnm.env
  data:
    image: "busybox"
    volumes:
      - /var/lib/postgresql/data
      - /app/.bundle
      - /app/vendor/bundle
