version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    environment:
      DOMAINS: 'tdnm.localhost -> http://app:3000'
      STAGE: 'local'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=root-password
      - DEFAULT_URL=https://tdnm.localhost
    env_file:
      - tdnm.env
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
    command: ["wait-for-it", "db:3306", "--", "bash", "-c", "bin/setup; rm tmp/pids/server.pid 2>/dev/null; bin/rails s -b '0.0.0.0'"]

  db:
    image: mysql:5
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
    env_file:
      - tdnm.env

volumes:
  mysql_data:
  bundle_cache:
