version: "2"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'tdnm.localhost -> http://app:3000'
      STAGE: 'local'
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    links:
      - db
    environment:
      - "DATABASE_URL=postgresql://postgres:postgresql_password@db:5432/tdnm"
      - "TRACKING_ID=UA-00000000-0"
      - "DEFAULT_URL=https://tdnm.localhost"
    depends_on:
      - db
    volumes:
      - .:/app
    volumes_from:
      - data
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: "postgres"
    volumes_from:
      - data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgresql_password"
      - "POSTGRES_DB=tdnm"
  data:
    image: "busybox"
    volumes:
      - /var/lib/postgresql/data
      - /app/.bundle
      - /app/vendor/bundle
