version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    environment:
      DOMAINS: 'tdnm.localhost -> http://app:3000'
      STAGE: 'local'
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    links:
      - db
    env_file:
      - tdnm.env
    volumes:
      - .:/app
      - bundler_cache:/app/vendor/bundle
    command: ["bash", "-c", "bin/setup; rm tmp/pids/server.pid 2>/dev/null; bin/rails s -b '0.0.0.0'"]

  db:
    image: mysql:5
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - tdnm.env

volumes:
  mysql_data:
  bundler_cache:
