# frozen_string_literal: true

# Skeleton for this file was generated by `bin/rails generate oneshot generate_new_slug`
# For copy and paste: `bin/rake oneshot:20210307_generate_new_slug`
namespace :oneshot do
  desc 'Generate new slug for all articles'
  task '20210307_generate_new_slug': :environment do
    ActiveRecord::Base.record_timestamps = false

    diary_slugs = %w(01 diary today)

    Article.find_each do |a|
      new_slug = a.published_on.strftime("%Y-%m-%d")

      unless diary_slugs.include?(a.slug)
        new_slug += "-#{a.slug}"
      end

      a.update!(new_slug: new_slug)
    end

    ActiveRecord::Base.record_timestamps = true
  end
end
