version: 2
jobs:
  build:
    working_directory: ~/tdnm

    docker:
      - image: circleci/ruby:2.6-node
        environment:
          DATABASE_URL: mysql2://root@127.0.0.1:3306/tdnm_test
          RAILS_ENV: test

      - image: circleci/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: tdnm_test

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path=vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: Setup Database
          command: bin/rails db:setup

      - run:
          name: Run tests
          command: bundle exec rake test

  publish_docker_image:
    working_directory: ~/tdnm

    machine:
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          command: docker build -t kenchan/tdnm:latest .
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          command: docker push kenchan/tdnm:latest

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish_docker_image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
