# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4cc1cc9005be5c5571dcac521728f978eb4274debce53118b369d232df2e501c4b7ad19fc9a641b023e1897a1f769516da6bca7340ffd49dce52c2d730baa3a

test:
  secret_key_base: a5db325e47bd8c1dc1d2e139735977d96c457f3f1d0aa06b9cb91281d7dabd1128f29257137aeaf90fc3f908e0f87537f21e0e603aaa0b416576816aa7319111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
