name: CI

on: [push]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Setup database
      run: bin/rails db:prepare
      env:
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: postgres

    - name: Run tests
      run: bin/rails test
      env:
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: postgres

    - name: Run system tests
      run: bin/rails test:system
      env:
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: postgres
