name: CI

on: [push]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root-password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -q libmysqlclient-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.66.0
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Setup database
      run: bin/rails db:prepare
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        DATABASE_PASSWORD: root-password

    - name: Run tests
      run: bin/rails test
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        DATABASE_PASSWORD: root-password

    - name: Run system tests
      run: bin/rails test:system
      env:
        DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        DATABASE_PASSWORD: root-password
