name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        sudo apt-get install libmysqlclient-dev
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3