name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        sudo apt-get install libmysqlclient-dev
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Setup database
      run: bin/rails db:prepare
    - name: Run tests
      run: bin/rails test